[2022-04-22T15:15:02.662] [ERROR] article.service - Oops [ProgrammerError]: [SQL5001] El calificador de columna o tabla CR400 no está definido.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'ProgrammerError',
  context: { sql: 'SELECT CR400.* FROM TRANSACCION;', params: undefined },
  cause: [Error: Error running instance method
  com.ibm.as400.access.AS400JDBCSQLSyntaxErrorException: [SQL5001] El calificador de columna o tabla CR400 no está definido.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:885)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:686)
  	at com.ibm.as400.access.AS400JDBCStatement.commonPrepare(AS400JDBCStatement.java:1823)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:362)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_com_ibm_as400_access_AS400JDBCSQLSyntaxErrorException {}
  },
  id: '981ae531-dd21-4e44-9055-d452e128135c'
}
[2022-04-22T15:15:24.603] [ERROR] article.service - Oops [ProgrammerError]: [SQL0104] Símbolo ; no válido. Símbolos válidos: , FROM INTO.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'ProgrammerError',
  context: { sql: 'SELECT CR-400.* FROM TRANSACCION;', params: undefined },
  cause: [Error: Error running instance method
  com.ibm.as400.access.AS400JDBCSQLSyntaxErrorException: [SQL0104] Símbolo ; no válido. Símbolos válidos: , FROM INTO.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:885)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:686)
  	at com.ibm.as400.access.AS400JDBCStatement.commonPrepare(AS400JDBCStatement.java:1823)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:362)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_com_ibm_as400_access_AS400JDBCSQLSyntaxErrorException {}
  },
  id: '96941b43-b05a-414a-8381-abfca1247e36'
}
[2022-04-22T15:16:45.055] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:18:55.777] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:19:57.067] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:20:25.866] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:21:07.710] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:22:21.511] [ERROR] index - nameBranch is not a function
[2022-04-22T15:23:16.733] [ERROR] index - this.extractBranchOfficeId is not a function
[2022-04-22T15:24:49.935] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:25:09.559] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:25:25.450] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:25:55.208] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:26:32.895] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:28:27.885] [ERROR] article.service - ReferenceError: array is not defined
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/services/article.service.js:16:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-04-22T15:28:45.177] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:31:37.180] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:32:05.363] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:32:20.333] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:42:00.941] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:42:41.046] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T15:43:20.315] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T16:36:18.274] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T16:36:47.475] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T16:37:00.387] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T18:11:23.166] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T18:45:41.525] [ERROR] article.service - Oops [ProgrammerError]: [SQL0206] No se ha encontrado la columna o variable global ID.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'ProgrammerError',
  context: {
    sql: 'SELECT id,FECHA  FROM TRANSACCION t WHERE date(FECHA)=CURRENT_DATE  ORDER BY FECHA DESC',
    params: undefined
  },
  cause: [Error: Error running instance method
  com.ibm.as400.access.AS400JDBCSQLSyntaxErrorException: [SQL0206] No se ha encontrado la columna o variable global ID.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:885)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:686)
  	at com.ibm.as400.access.AS400JDBCStatement.commonPrepare(AS400JDBCStatement.java:1823)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:362)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_com_ibm_as400_access_AS400JDBCSQLSyntaxErrorException {}
  },
  id: '1085ea68-ab91-4ba6-9c76-70faaeb4e85b'
}
[2022-04-22T18:47:08.247] [ERROR] article.service - Oops [ProgrammerError]: [SQL0206] No se ha encontrado la columna o variable global ID.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'ProgrammerError',
  context: {
    sql: 'SELECT id,FECHA  FROM TRANSACCION t WHERE date(FECHA)=CURRENT_DATE  ORDER BY FECHA DESC',
    params: undefined
  },
  cause: [Error: Error running instance method
  com.ibm.as400.access.AS400JDBCSQLSyntaxErrorException: [SQL0206] No se ha encontrado la columna o variable global ID.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:885)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:686)
  	at com.ibm.as400.access.AS400JDBCStatement.commonPrepare(AS400JDBCStatement.java:1823)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:362)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_com_ibm_as400_access_AS400JDBCSQLSyntaxErrorException {}
  },
  id: '7480e651-99d2-4b66-ab13-0db9f158a522'
}
[2022-04-22T18:52:21.775] [ERROR] article.service - Oops [ProgrammerError]: [SQL0206] No se ha encontrado la columna o variable global ID.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/articleClient/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'ProgrammerError',
  context: {
    sql: 'SELECT ID,FECHA  FROM TRANSACCION t WHERE date(FECHA)=CURRENT_DATE  ORDER BY FECHA DESC',
    params: undefined
  },
  cause: [Error: Error running instance method
  com.ibm.as400.access.AS400JDBCSQLSyntaxErrorException: [SQL0206] No se ha encontrado la columna o variable global ID.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:885)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:686)
  	at com.ibm.as400.access.AS400JDBCStatement.commonPrepare(AS400JDBCStatement.java:1823)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:362)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_com_ibm_as400_access_AS400JDBCSQLSyntaxErrorException {}
  },
  id: '3f446c01-61b1-443c-9912-b735ca57ac1e'
}
[2022-04-22T18:53:12.926] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-22T18:54:49.569] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T11:23:18.835] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T11:26:04.146] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T11:30:10.860] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T11:30:37.128] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T11:30:49.961] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T11:43:13.078] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T11:46:39.520] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T11:49:50.512] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T12:13:33.343] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T12:14:49.194] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T12:58:20.617] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T13:04:47.602] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T13:04:52.429] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T13:46:00.576] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T13:48:39.362] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T13:54:22.181] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T15:45:03.285] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T15:48:50.832] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T17:00:45.768] [ERROR] article.service - Oops [ProgrammerError]: [SQL0104] Símbolo <FIN DE SENTENCIA> no válido. Símbolos válidos: , FROM INTO.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'ProgrammerError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.*',
    params: undefined
  },
  cause: [Error: Error running instance method
  com.ibm.as400.access.AS400JDBCSQLSyntaxErrorException: [SQL0104] Símbolo <FIN DE SENTENCIA> no válido. Símbolos válidos: , FROM INTO.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:885)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:686)
  	at com.ibm.as400.access.AS400JDBCStatement.commonPrepare(AS400JDBCStatement.java:1823)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:362)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_com_ibm_as400_access_AS400JDBCSQLSyntaxErrorException {}
  },
  id: '181bf2a2-dbe1-4e1b-946c-172de8f02d43'
}
[2022-04-23T17:01:21.521] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T17:01:25.349] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T17:42:41.269] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T17:43:18.277] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T17:46:11.100] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T17:51:38.363] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T17:54:20.741] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-23T19:10:02.573] [ERROR] article.service - Oops [ProgrammerError]: [SQL0199] Palabra clave ORDER inesperada. Símbolos válidos: FOR USE SKIP WAIT WITH OPTIMIZE.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'ProgrammerError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA LIMIT 5 ORDER BY m.ID desc',
    params: undefined
  },
  cause: [Error: Error running instance method
  com.ibm.as400.access.AS400JDBCSQLSyntaxErrorException: [SQL0199] Palabra clave ORDER inesperada. Símbolos válidos: FOR USE SKIP WAIT WITH OPTIMIZE.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:885)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:686)
  	at com.ibm.as400.access.AS400JDBCStatement.commonPrepare(AS400JDBCStatement.java:1823)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:362)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_com_ibm_as400_access_AS400JDBCSQLSyntaxErrorException {}
  },
  id: 'cc3d81e4-f507-4984-a77d-03eb7dc1c061'
}
[2022-04-23T19:10:45.776] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T15:15:56.926] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T16:28:14.001] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T16:29:51.457] [ERROR] index - results is not defined
[2022-04-24T16:33:10.604] [ERROR] index - results is not defined
[2022-04-24T16:39:06.181] [ERROR] article.service - ReferenceError: articles is not defined
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/services/article.service.js:17:37
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2022-04-24T16:40:08.383] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T16:41:35.212] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T16:41:49.845] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T16:42:43.241] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T16:48:02.016] [ERROR] index - results is not defined
[2022-04-24T16:48:43.770] [ERROR] index - results is not defined
[2022-04-24T16:53:01.968] [ERROR] index - results is not defined
[2022-04-24T16:54:37.935] [ERROR] index - results is not defined
[2022-04-24T16:55:31.143] [ERROR] index - numeroDeIdTransaccion is not defined
[2022-04-24T16:56:00.165] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T16:56:34.525] [ERROR] index - results is not defined
[2022-04-24T16:56:56.397] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T18:07:35.863] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T18:29:37.055] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T18:32:16.648] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T18:32:56.870] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T18:34:58.192] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T18:35:51.796] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T18:43:54.241] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T18:51:46.096] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T18:57:56.640] [ERROR] index - articles is not defined
[2022-04-24T18:57:56.740] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '7f66c18b-b847-4281-8bc1-3cc2e22d54be'
}
[2022-04-24T18:58:47.812] [ERROR] index - articles is not defined
[2022-04-24T18:58:47.849] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '972aea6a-7221-46b3-86e7-091284d07c4d'
}
[2022-04-24T18:59:59.897] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T19:02:17.727] [ERROR] index - articles is not defined
[2022-04-24T19:02:17.747] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '8eaf0e39-ed0e-4335-8a3e-0e01522273fc'
}
[2022-04-24T19:04:07.052] [ERROR] index - articles is not defined
[2022-04-24T19:04:07.076] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '6d231193-1dd4-4ebb-98ac-aac12f760e4f'
}
[2022-04-24T19:06:09.557] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '3d51f674-3b26-4c34-9593-60a7a389bb35'
}
[2022-04-24T19:06:48.836] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '8c3a9bd6-4def-45bd-bc0a-12815c9103f1'
}
[2022-04-24T19:08:10.515] [ERROR] index - results is not defined
[2022-04-24T19:08:10.548] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '21148d5e-74d6-4934-b00c-d6be774ded73'
}
[2022-04-24T19:10:10.769] [ERROR] index - results is not defined
[2022-04-24T19:10:10.794] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '13710110-7c2f-4985-a874-69f3c571640f'
}
[2022-04-24T19:10:48.983] [ERROR] index - results is not defined
[2022-04-24T19:10:49.007] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: 'c35a9bbd-e9d8-4051-8d5b-9db5937944ce'
}
[2022-04-24T19:13:23.878] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '31acd074-9274-4152-8c42-36534abe6ab9'
}
[2022-04-24T19:20:16.416] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '485ca7f4-8bdd-4040-b9ab-848fb4b7941d'
}
[2022-04-24T19:22:10.513] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: 'a989a252-9d73-47f9-9cc6-80ad3d649906'
}
[2022-04-24T19:22:24.142] [ERROR] article.service - Oops [OperationalError]: The application requester cannot establish the connection. (Connection was dropped unexpectedly.)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  com.ibm.as400.access.ConnectionPoolException: The application requester cannot establish the connection. (Connection was dropped unexpectedly.)
  	at com.ibm.as400.access.AS400JDBCConnectionPool.fill(AS400JDBCConnectionPool.java:360)
  	at com.ibm.as400.access.AS400JDBCConnectionPool.getPooledConnection(AS400JDBCConnectionPool.java:501)
  	at com.ibm.as400.access.AS400JDBCConnectionPool.getConnection(AS400JDBCConnectionPool.java:456)
  	at nodejt400.Pool.getConnection(Unknown Source)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  Caused by: java.sql.SQLException: The application requester cannot establish the connection. (Connection was dropped unexpectedly.)
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:553)
  	at com.ibm.as400.access.AS400JDBCConnection.setProperties(AS400JDBCConnection.java:3391)
  	at com.ibm.as400.access.AS400JDBCDataSource.getConnection(AS400JDBCDataSource.java:756)
  	at com.ibm.as400.access.AS400JDBCDataSource.getConnection(AS400JDBCDataSource.java:614)
  	at com.ibm.as400.access.AS400JDBCConnectionPool.createPooledConnection(AS400JDBCConnectionPool.java:307)
  	at com.ibm.as400.access.AS400JDBCConnectionPool.fill(AS400JDBCConnectionPool.java:344)
  	... 9 more
  ] {
    cause: nodeJava_com_ibm_as400_access_ConnectionPoolException {}
  },
  id: '5dc43c63-85a2-40b7-ae14-9adaca219161'
}
[2022-04-24T19:38:38.153] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.send(AS400JDBCConnection.java:2733)
  	at com.ibm.as400.access.AS400JDBCConnection.send(AS400JDBCConnection.java:2708)
  	at com.ibm.as400.access.JDCursor.close(JDCursor.java:117)
  	at com.ibm.as400.access.AS400JDBCStatement.notifyClose(AS400JDBCStatement.java:3750)
  	at com.ibm.as400.access.AS400JDBCResultSet.close(AS400JDBCResultSet.java:520)
  	at com.ibm.as400.access.AS400JDBCStatement.closeResultSet(AS400JDBCStatement.java:682)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:434)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '53730342-cd3e-4c06-a285-d3b4bd30c3b5'
}
[2022-04-24T21:01:16.727] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: 'afb737f2-8922-444c-9fa5-61ba4a58c2a0'
}
[2022-04-24T21:29:00.699] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: 'd53393d5-ca7f-4a28-a4f8-7691787a9ac1'
}
[2022-04-24T21:31:58.174] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '387633b7-fa35-4380-b756-4ef448708d63'
}
[2022-04-24T21:36:44.029] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T21:38:18.779] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T22:20:21.122] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T23:17:28.801] [ERROR] index - Cannot read property 'substring' of undefined
[2022-04-24T23:26:31.074] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: 'a53d8080-a677-47f3-a820-d2693dc6fda7'
}
[2022-04-24T23:27:01.616] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: 'f9ba08ba-826f-4408-a7fa-c2d9deed6055'
}
[2022-04-24T23:55:31.409] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '97873f62-3f63-42b4-9bac-720d6fa5189d'
}
[2022-04-25T11:12:52.255] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '6fb9e163-865c-497b-8a24-be5daa823b3f'
}
[2022-04-25T11:21:15.312] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.send(AS400JDBCConnection.java:2733)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:541)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '1688cedb-2938-4c7d-83b4-aab16e0d4d33'
}
[2022-04-25T11:21:15.314] [ERROR] article.controller - The connection does not exist.
[2022-04-25T11:21:15.315] [ERROR] index - The connection does not exist.
[2022-04-25T12:28:38.900] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.send(AS400JDBCConnection.java:2733)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:541)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '9391d343-c96a-4a55-8ea3-3ca81f6b08ad'
}
[2022-04-25T12:28:38.908] [ERROR] article.controller - The connection does not exist.
[2022-04-25T12:28:38.909] [ERROR] index - The connection does not exist.
[2022-04-25T13:24:07.902] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.send(AS400JDBCConnection.java:2733)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:541)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '225782a6-eed6-4d2a-a854-620e3dc477da'
}
[2022-04-25T13:24:07.906] [ERROR] article.controller - The connection does not exist.
[2022-04-25T13:24:07.907] [ERROR] index - The connection does not exist.
[2022-04-25T13:49:21.169] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.send(AS400JDBCConnection.java:2733)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:541)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '6b63f4b4-1b0f-4a4b-a87b-c04ee9fe92e5'
}
[2022-04-25T13:49:21.172] [ERROR] article.controller - The connection does not exist.
[2022-04-25T13:49:21.173] [ERROR] index - The connection does not exist.
[2022-04-25T13:50:41.755] [ERROR] index - Cannot read property 'ID_TIPOACREENCIAOPERACION' of undefined
[2022-04-25T13:52:00.460] [ERROR] index - Cannot read property 'ID_MOVIENTOACREENCIA' of undefined
[2022-04-25T13:52:29.943] [ERROR] index - Cannot read property 'ID_MOVIMIENTOACREENCIA' of undefined
[2022-04-25T13:53:16.268] [ERROR] index - Cannot read property 'ID_MOVIMIENTOACREENCIA' of undefined
[2022-04-25T13:55:04.295] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.send(AS400JDBCConnection.java:2733)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:541)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '3eb45425-31b7-4fd3-9756-37ba51c5364a'
}
[2022-04-25T13:55:04.297] [ERROR] article.controller - The connection does not exist.
[2022-04-25T13:55:04.297] [ERROR] index - The connection does not exist.
[2022-04-25T13:56:12.237] [ERROR] index - Cannot read property 'ID_MOVIMIENTOACREENCIA' of undefined
[2022-04-25T13:56:42.354] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.send(AS400JDBCConnection.java:2733)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:541)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: 'cfc85c95-773f-4985-8f91-42a0765f7505'
}
[2022-04-25T13:56:42.356] [ERROR] article.controller - The connection does not exist.
[2022-04-25T13:56:42.356] [ERROR] index - The connection does not exist.
[2022-04-25T13:58:18.124] [ERROR] index - Cannot read property 'ID' of undefined
[2022-04-25T14:00:56.321] [ERROR] index - Cannot read property 'ID_MOVIMIENTOACREENCIA' of undefined
[2022-04-25T14:02:09.676] [ERROR] index - Cannot read property 'ID_MOVIMIENTOACREENCIA' of undefined
[2022-04-25T14:02:37.794] [ERROR] index - Cannot read property 'ID_MOVIMIENTOACREENCIA' of undefined
[2022-04-25T14:14:03.905] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.send(AS400JDBCConnection.java:2733)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:541)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '1450721d-254c-48d2-b8c8-5f32836edee1'
}
[2022-04-25T14:14:03.907] [ERROR] article.controller - The connection does not exist.
[2022-04-25T14:14:03.909] [ERROR] index - The connection does not exist.
[2022-04-25T14:42:13.841] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.send(AS400JDBCConnection.java:2733)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:541)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: 'ba1a2b0c-55d9-432b-bdf3-a1c9e016c07b'
}
[2022-04-25T14:42:13.844] [ERROR] article.controller - The connection does not exist.
[2022-04-25T14:42:13.844] [ERROR] index - The connection does not exist.
[2022-04-25T14:44:09.607] [ERROR] index - Cannot read property 'ID_MOVIMIENTOACREENCIA' of undefined
[2022-04-25T14:44:52.895] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  com.ibm.as400.access.ConnectionPoolException: The connection does not exist.
  	at com.ibm.as400.access.AS400JDBCConnectionPool.getConnection(AS400JDBCConnectionPool.java:465)
  	at nodejt400.Pool.getConnection(Unknown Source)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  Caused by: java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCPooledConnection.getConnectionHandle(AS400JDBCPooledConnection.java:269)
  	at com.ibm.as400.access.AS400JDBCPooledConnection.getConnection(AS400JDBCPooledConnection.java:250)
  	at com.ibm.as400.access.AS400JDBCConnectionPool.getConnection(AS400JDBCConnectionPool.java:461)
  	... 7 more
  ] {
    cause: nodeJava_com_ibm_as400_access_ConnectionPoolException {}
  },
  id: '1f1ccd02-2253-4d18-ae24-bb0157565772'
}
[2022-04-25T14:44:52.900] [ERROR] article.controller - The connection does not exist.
[2022-04-25T14:44:52.900] [ERROR] index - The connection does not exist.
[2022-04-25T18:30:25.934] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  com.ibm.as400.access.ConnectionPoolException: The connection does not exist.
  	at com.ibm.as400.access.AS400JDBCConnectionPool.getConnection(AS400JDBCConnectionPool.java:465)
  	at nodejt400.Pool.getConnection(Unknown Source)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  Caused by: java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCPooledConnection.getConnectionHandle(AS400JDBCPooledConnection.java:269)
  	at com.ibm.as400.access.AS400JDBCPooledConnection.getConnection(AS400JDBCPooledConnection.java:250)
  	at com.ibm.as400.access.AS400JDBCConnectionPool.getConnection(AS400JDBCConnectionPool.java:461)
  	... 7 more
  ] {
    cause: nodeJava_com_ibm_as400_access_ConnectionPoolException {}
  },
  id: 'cee14194-144a-4074-869a-528bd453f49b'
}
[2022-04-25T18:30:25.935] [ERROR] article.controller - The connection does not exist.
[2022-04-25T18:30:25.936] [ERROR] index - The connection does not exist.
[2022-04-25T19:01:47.148] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.send(AS400JDBCConnection.java:2733)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:541)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: 'f12dba7c-2fbe-424a-ad00-5b7a61d871ff'
}
[2022-04-25T19:01:47.154] [ERROR] article.controller - The connection does not exist.
[2022-04-25T19:01:47.155] [ERROR] index - The connection does not exist.
[2022-04-25T19:33:15.607] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '24918e7c-400d-408c-bf13-235b46f83f80'
}
[2022-04-25T19:35:27.397] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '930595a9-4e7d-4996-b2c6-ad5324f0966d'
}
[2022-04-25T19:39:37.228] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '0c3912f1-c869-43ff-b637-f158c0e32dc1'
}
[2022-04-25T19:42:17.454] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '58d40cf1-5d95-474e-8a20-4eefc0aec7c3'
}
[2022-04-25T20:36:48.023] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.sendAndReceive(AS400JDBCConnection.java:2981)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:485)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: 'b0043fb8-d238-424d-859b-ed74b140f3fe'
}
[2022-04-25T20:37:09.306] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCConnection.checkOpen(AS400JDBCConnection.java:496)
  	at com.ibm.as400.access.AS400JDBCConnection.send(AS400JDBCConnection.java:2733)
  	at com.ibm.as400.access.AS400JDBCStatement.close(AS400JDBCStatement.java:541)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.close(AS400JDBCPreparedStatement.java:683)
  	at com.ibm.as400.access.AS400JDBCPreparedStatement.<init>(AS400JDBCPreparedStatement.java:364)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2206)
  	at com.ibm.as400.access.AS400JDBCConnection.prepareStatement(AS400JDBCConnection.java:2005)
  	at com.ibm.as400.access.AS400JDBCConnectionHandle.prepareStatement(AS400JDBCConnectionHandle.java:899)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  ] {
    cause: nodeJava_java_sql_SQLException {}
  },
  id: '02e4d04c-f49b-4dc8-8d1a-c87f1e510819'
}
[2022-04-26T12:15:52.219] [ERROR] article.service - Oops [OperationalError]: The connection does not exist.
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/node-jt400/dist/lib/jt400.js:83:15
    at _rejected (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:864:24)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:890:30
    at Promise.when (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:808:41)
    at /home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:624:44
    at runSingle (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:137:13)
    at flush (/home/lvina/Documentos/En_Desarrollo/microservicios/serviceSoapGetComint/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  fullStack: [Function],
  category: 'OperationalError',
  context: {
    sql: 'SELECT  a.ID AS ID_ACREENCIA , a.NUMERO_IDENTIFICACION_CLIENTE AS NUMERO_IDENTIFICACION_CLIENTE, m.* FROM CR400.ACREENCIA a INNER JOIN CR400.MOVIMIENTOACREENCIA m ON a.ID  = m.ID_ACREENCIA ORDER BY m.ID desc LIMIT 5',
    params: undefined
  },
  cause: [Error: Error running instance method
  com.ibm.as400.access.ConnectionPoolException: The connection does not exist.
  	at com.ibm.as400.access.AS400JDBCConnectionPool.getConnection(AS400JDBCConnectionPool.java:465)
  	at nodejt400.Pool.getConnection(Unknown Source)
  	at nodejt400.JdbcJsonClient.query(Unknown Source)
  	at nodejt400.JT400.query(Unknown Source)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  Caused by: java.sql.SQLException: The connection does not exist.
  	at com.ibm.as400.access.JDError.createSQLExceptionSubClass(JDError.java:824)
  	at com.ibm.as400.access.JDError.throwSQLException(JDError.java:412)
  	at com.ibm.as400.access.AS400JDBCPooledConnection.getConnectionHandle(AS400JDBCPooledConnection.java:269)
  	at com.ibm.as400.access.AS400JDBCPooledConnection.getConnection(AS400JDBCPooledConnection.java:250)
  	at com.ibm.as400.access.AS400JDBCConnectionPool.getConnection(AS400JDBCConnectionPool.java:461)
  	... 7 more
  ] {
    cause: nodeJava_com_ibm_as400_access_ConnectionPoolException {}
  },
  id: '3032249a-22ff-4cb2-a4af-a4179106c143'
}
[2022-04-26T12:46:29.522] [ERROR] article.controller - resp is not defined
